# Generated by Django 3.2.8 on 2021-10-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoadProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=10, max_digits=19)),
                ('width', models.DecimalField(decimal_places=10, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('road_type', models.CharField(max_length=250)),
                ('name_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.road')),
            ],
        ),
    ]
