# Generated by Django 3.2.8 on 2021-10-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadproperties',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
